/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service + provider status snapshot
         * @description Return app metadata and per-provider configuration status.
         */
        get: operations["get_system_info_api_v1_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness + dependency health
         * @description Return a coarse health snapshot.
         */
        get: operations["get_system_health_api_v1_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List collections
         * @description Cursor-paginated list of collections.
         */
        get: operations["list_collections_api_v1_collections_get"];
        put?: never;
        /**
         * Create a collection
         * @description Create a new collection (persists a BM25 index marker).
         */
        post: operations["create_collection_api_v1_collections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single collection
         * @description Fetch a single collection by ID.
         */
        get: operations["get_collection_api_v1_collections__collection_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a collection
         * @description Delete a collection and all of its documents.
         */
        delete: operations["delete_collection_api_v1_collections__collection_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update a collection
         * @description Update mutable knowledge-base metadata.
         */
        patch: operations["update_collection_api_v1_collections__collection_id__patch"];
        trace?: never;
    };
    "/api/v1/collections/{collection_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List documents in a collection
         * @description Cursor-paginated list of documents belonging to a collection.
         */
        get: operations["list_collection_documents_api_v1_collections__collection_id__documents_get"];
        put?: never;
        /**
         * Upload documents and start ingestion
         * @description Upload one or more documents to a collection and start ingestion.
         *
         *     Two mutually-exclusive modes on the same endpoint:
         *
         *     - **Single** (legacy, M2): send ``file``. Returns ``202`` with a
         *       ``DocumentUploadResponse``; behavior is unchanged from M2 except the
         *       addition of a file-extension check (415) beside the MIME check
         *       (double validation per DEV_SPEC).
         *     - **Batch** (M5): send ``files[]``. All files go to the same
         *       collection. Returns ``202`` with a ``BatchUploadResponse`` carrying
         *       a ``batch_id`` and one result per file (``accepted`` → ``task_id``
         *       to poll, ``skipped`` → duplicate, ``rejected`` → structured error).
         *       A single file's validation / ingestion failure never blocks the
         *       others.
         *
         *     Limits: per-file size ``WEB_API_UPLOAD_MAX_BYTES`` (413), batch file
         *     count ``WEB_API_UPLOAD_MAX_BATCH_FILES`` and batch total
         *     ``WEB_API_UPLOAD_MAX_BATCH_BYTES`` (413), extension + MIME allow-lists
         *     (415). Unknown collection → 404. There is no SSE — clients poll
         *     ``GET /tasks/{id}`` for each accepted file.
         */
        post: operations["upload_collection_document_api_v1_collections__collection_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single document
         * @description Fetch document detail by ID.
         */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a document (coordinated)
         * @description Coordinated delete across vector store + BM25 + image storage.
         */
        delete: operations["delete_document_api_v1_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get ingestion task status
         * @description Return the current status of an ingestion task.
         *
         *     The task registry is process-local. A task that cannot be found
         *     returns ``404`` with envelope code ``TASK_NOT_FOUND``. Frontends
         *     poll this endpoint after ``POST /collections/{id}/documents`` until
         *     the status reaches ``succeeded`` or ``failed``.
         */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * RAG overview metrics
         * @description Aggregate quality, latency and ingestion signals for the overview UI.
         */
        get: operations["get_overview_metrics_api_v1_metrics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a hybrid query against a collection
         * @description Run retrieval and return citations + diagnostics.
         *
         *     M3: ``collection=name`` routes the query to the per-collection
         *     ``HybridSearch`` (EngineCache) — fixing the v0.2 limitation where
         *     every collection silently queried the default index.
         */
        post: operations["create_query_api_v1_collections__collection_id__queries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}/queries/async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a query asynchronously
         * @description Submit a query and return immediately.
         *
         *     M3 batch 2: the query runs in a background thread; poll
         *     ``GET /queries/{query_id}/result`` for the outcome. ``task_id``
         *     equals ``query_id`` (and the trace id).
         */
        post: operations["create_async_query_api_v1_collections__collection_id__queries_async_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queries/{query_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an async query result
         * @description Poll an async query (M3 batch 2).
         *
         *     ``pending`` / ``running`` → keep polling; ``succeeded`` populates
         *     ``result``; ``failed`` populates ``error``. Unknown ids return 404
         *     ``QUERY_NOT_FOUND``.
         */
        get: operations["get_async_query_result_api_v1_queries__query_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queries/{query_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a query trace
         * @description Return the per-stage trace for a previously run query.
         *
         *     Every query recorded by the Web API stores its trace under
         *     ``query_id == trace_id``, so this is a straight store lookup.
         */
        get: operations["get_query_trace_api_v1_queries__query_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestions/{ingestion_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an ingestion trace
         * @description Return the per-stage trace for a previously run ingestion.
         *
         *     Ingestion traces are recorded with ``trace_id == task_id``. When the
         *     trace is missing but the task still exists (e.g. recorded before this
         *     feature, or trace persistence failed), return 200 with empty stages —
         *     the ingestion *record* is real even if its timeline is gone.
         */
        get: operations["get_ingestion_trace_api_v1_ingestions__ingestion_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch an indexed image
         * @description Return image bytes for the given image ID.
         */
        get: operations["get_image_api_v1_images__image_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List MCP API keys */
        get: operations["list_mcp_keys_api_v1_mcp_keys_get"];
        put?: never;
        /** Create an MCP API key */
        post: operations["create_mcp_key_api_v1_mcp_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp-keys/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an MCP API key */
        delete: operations["delete_mcp_key_api_v1_mcp_keys__name__delete"];
        options?: never;
        head?: never;
        /** Rename an MCP API key */
        patch: operations["rename_mcp_key_api_v1_mcp_keys__name__patch"];
        trace?: never;
    };
    "/api/v1/mcp-keys/{name}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate an MCP API key */
        post: operations["rotate_mcp_key_api_v1_mcp_keys__name__rotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp-keys/{name}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke an MCP API key */
        post: operations["revoke_mcp_key_api_v1_mcp_keys__name__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AsyncQueryAccepted
         * @description ``POST /collections/{id}/queries/async`` response (M3 batch 2).
         *
         *     Returns immediately with the query id; poll ``GET /queries/{id}/result``
         *     until it reaches ``succeeded`` / ``failed``. ``task_id`` equals
         *     ``query_id`` (and the trace id) so one id drives result + trace.
         * @example {
         *       "query_id": "9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d",
         *       "status": "accepted",
         *       "task_id": "9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d"
         *     }
         */
        AsyncQueryAccepted: {
            /**
             * Query Id
             * Format: uuid
             */
            query_id: string;
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /**
             * Status
             * @default accepted
             * @constant
             */
            status: "accepted";
        };
        /**
         * AsyncQueryResult
         * @description ``GET /queries/{query_id}/result`` response (M3 batch 2).
         *
         *     Poll until ``status`` is ``succeeded`` (``result`` populated) or
         *     ``failed`` (``error`` populated). ``pending`` / ``running`` mean the
         *     background query is still in flight.
         * @example {
         *       "query_id": "9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d",
         *       "result": {
         *         "citations": [],
         *         "diagnostics": {},
         *         "query_id": "…"
         *       },
         *       "status": "succeeded"
         *     }
         */
        AsyncQueryResult: {
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "succeeded" | "failed";
            /**
             * Query Id
             * Format: uuid
             */
            query_id: string;
            /** @description The query response, present only when ``status`` is ``succeeded``. */
            result?: components["schemas"]["QueryResponse"] | null;
            /** @description Structured error, present only when ``status`` is ``failed``. */
            error?: components["schemas"]["TaskError"] | null;
        };
        /**
         * BatchFileResult
         * @description One file's result inside a ``BatchUploadResponse`` (M5).
         * @example {
         *       "document_id": "7d4a1c3e-2b0a-4d2c-8e9f-1a2b3c4d5e6f",
         *       "filename": "employee-handbook.pdf",
         *       "size_bytes": 1845632,
         *       "status": "accepted",
         *       "task_id": "1f2e3d4c-5b6a-4c8d-9e0f-1a2b3c4d5e6f"
         *     }
         */
        BatchFileResult: {
            /**
             * Filename
             * @description Original file name.
             */
            filename: string;
            /**
             * Document Id
             * @description Stable document UUID (``uuid5`` of collection+source path). ``None`` for rejected files (never written to storage).
             */
            document_id?: string | null;
            /**
             * Task Id
             * @description Ingestion task to poll for ``accepted`` files; ``None`` for ``skipped``/``rejected``.
             */
            task_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "skipped" | "rejected";
            /**
             * Size Bytes
             * @description Raw file size in bytes.
             * @default 0
             */
            size_bytes: number;
            /** @description Structured error for ``rejected`` files. Same shape as the HTTP error envelope — branch on ``error.code`` (``UNSUPPORTED_FILE_TYPE`` / ``UNSUPPORTED_MEDIA_TYPE`` / ``FILE_TOO_LARGE`` / ``DUPLICATE_FILENAME``). */
            error?: components["schemas"]["TaskError"] | null;
        };
        /**
         * BatchUploadResponse
         * @description ``POST /collections/{id}/documents`` batch response (M5).
         *
         *     One batch uploads many files to the same collection. Each file is
         *     validated and submitted independently — a single rejection never
         *     blocks the others, and accepted files each carry their own
         *     ``task_id`` for async polling. ``total == accepted + skipped + rejected``.
         * @example {
         *       "accepted": 2,
         *       "batch_id": "6c9f3d5a-8b1e-4a2d-9c7f-0e5d4a3b2c1a",
         *       "collection_id": "b2c1f0e8-1234-5678-9abc-def012345678",
         *       "files": [
         *         {
         *           "document_id": "7d4a1c3e-2b0a-4d2c-8e9f-1a2b3c4d5e6f",
         *           "filename": "a.pdf",
         *           "size_bytes": 1024,
         *           "status": "accepted",
         *           "task_id": "1f2e3d4c-5b6a-4c8d-9e0f-1a2b3c4d5e6f"
         *         },
         *         {
         *           "document_id": "8e5b2d4f-3c1e-4b3f-9d0e-2b3c4d5e6f7a",
         *           "filename": "b.md",
         *           "size_bytes": 2048,
         *           "status": "accepted",
         *           "task_id": "2f3e4d5c-6b7a-4c9d-8e0f-3b4c5d6e7f8b"
         *         },
         *         {
         *           "error": {
         *             "code": "UNSUPPORTED_FILE_TYPE",
         *             "details": {},
         *             "message": "Unsupported file extension .txt"
         *           },
         *           "filename": "bad.txt",
         *           "size_bytes": 512,
         *           "status": "rejected"
         *         }
         *       ],
         *       "rejected": 1,
         *       "skipped": 0,
         *       "total": 3
         *     }
         */
        BatchUploadResponse: {
            /**
             * Batch Id
             * Format: uuid
             * @description Correlation id for this batch.
             */
            batch_id: string;
            /**
             * Collection Id
             * Format: uuid
             * @description Target collection UUID.
             */
            collection_id: string;
            /**
             * Total
             * @description Number of files in the batch.
             */
            total: number;
            /**
             * Accepted
             * @description Files accepted as new tasks.
             */
            accepted: number;
            /**
             * Skipped
             * @description Files skipped as duplicates (already ingested).
             */
            skipped: number;
            /**
             * Rejected
             * @description Files rejected by boundary validation.
             */
            rejected: number;
            /**
             * Files
             * @description Per-file results, in submission order.
             */
            files: components["schemas"]["BatchFileResult"][];
        };
        /** Body_upload_collection_document_api_v1_collections__collection_id__documents_post */
        Body_upload_collection_document_api_v1_collections__collection_id__documents_post: {
            /**
             * File
             * @description Single document file (PDF / Markdown).
             */
            file?: string | null;
            /**
             * Files
             * @description Batch of documents; all go to this collection.
             */
            files?: string[] | null;
        };
        /**
         * Citation
         * @description One retrievable chunk referenced by the answer.
         *
         *     The 1-based index matches the ``[1]`` markers in the answer text so
         *     the Web UI can render clickable inline references.
         * @example {
         *       "chunk_id": "d2c3v4b5n6m7",
         *       "document_id": "7d4a1c3e-2b0a-4d2c-8e9f-1a2b3c4d5e6f",
         *       "document_name": "employee-handbook.pdf",
         *       "images": [
         *         {
         *           "caption": "年假申请流程图",
         *           "id": "img-001",
         *           "url": "/api/v1/images/img-001"
         *         }
         *       ],
         *       "index": 1,
         *       "page": 12,
         *       "scores": {
         *         "dense": 0.81,
         *         "fusion": 0.031,
         *         "rerank": 0.91,
         *         "sparse": 8.2
         *       },
         *       "text": "员工年假标准：入职满 1 年不满 10 年，每年 5 天；…"
         *     }
         */
        Citation: {
            /**
             * Index
             * @description 1-based position in the citation list.
             */
            index: number;
            /** Chunk Id */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Document Name
             * @description Human-readable document name (filename).
             */
            document_name: string;
            /**
             * Page
             * @description Source page number when applicable.
             */
            page?: number | null;
            /**
             * Text
             * @description Raw chunk text for snippet rendering.
             */
            text: string;
            scores?: components["schemas"]["CitationScores"];
            /** Images */
            images?: components["schemas"]["CitationImage"][];
        };
        /**
         * CitationImage
         * @description Image associated with a citation.
         *
         *     ``url`` is always a *relative* path (``/api/v1/images/{id}``) so the
         *     frontend can resolve it against the configured API base URL.
         *     Local filesystem paths MUST NOT leak into the API.
         */
        CitationImage: {
            /**
             * Id
             * @description Stable image identifier.
             */
            id: string;
            /**
             * Url
             * @description Relative path, e.g. ``/api/v1/images/abc-123``.
             * @example /api/v1/images/abc-123
             */
            url: string;
            /**
             * Caption
             * @description Image caption (if multimodal enrichment was enabled).
             */
            caption?: string | null;
        };
        /**
         * CitationScores
         * @description Per-stage scores for a single citation.
         *
         *     Every field is nullable because a chunk may appear in only one
         *     retrieval branch (e.g. dense-only query) or have no rerank applied.
         */
        CitationScores: {
            /**
             * Dense
             * @description Cosine similarity from the dense retriever (0–1).
             */
            dense?: number | null;
            /**
             * Sparse
             * @description BM25 score from the sparse retriever (raw, not normalised).
             */
            sparse?: number | null;
            /**
             * Fusion
             * @description Reciprocal Rank Fusion score — sum of ``1 / (k + rank_i)`` across the input rankings (default ``k = 60``). **Higher is better.** Range is roughly ``(0, len(rankings)]``; values for the top hit are typically small (e.g. ~0.016 for k=60). See ``src/core/query_engine/fusion.py::reciprocal_rank_fusion``.
             */
            fusion?: number | null;
            /**
             * Rerank
             * @description Score from the rerank stage (provider-specific range).
             */
            rerank?: number | null;
        };
        /**
         * CollectionCreateRequest
         * @description ``POST /collections`` body.
         * @example {
         *       "description": "Internal HR & policies.",
         *       "name": "company-handbook"
         *     }
         */
        CollectionCreateRequest: {
            /**
             * Name
             * @description Human-readable collection name. Must be unique.
             */
            name: string;
            /**
             * Description
             * @description Optional description.
             */
            description?: string | null;
        };
        /**
         * CollectionDetail
         * @description ``GET /collections/{id}`` response — same as summary for now.
         *
         *     Kept as a separate type so future fields (e.g. configuration overrides)
         *     can be added without breaking the list response.
         * @example {
         *       "chunk_count": 1820,
         *       "created_at": "2026-07-15T03:11:08.012Z",
         *       "description": "Internal HR & policies.",
         *       "document_count": 12,
         *       "id": "b2c1f0e8-1234-5678-9abc-def012345678",
         *       "name": "company-handbook",
         *       "updated_at": "2026-07-31T08:25:42.001Z"
         *     }
         */
        CollectionDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Name
             * @description Human-readable collection name.
             */
            name: string;
            /**
             * Description
             * @description Optional long-form description.
             */
            description?: string | null;
            /**
             * Document Count
             * @description Number of documents currently indexed.
             * @default 0
             */
            document_count: number;
            /**
             * Chunk Count
             * @description Total chunks indexed across all documents.
             * @default 0
             */
            chunk_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CollectionListResponse
         * @description ``GET /collections`` response — page of summaries.
         *
         *     Example (empty list)::
         *
         *         {
         *           "items": [],
         *           "page_info": {"next_cursor": null, "has_more": false}
         *         }
         * @example {
         *       "items": [],
         *       "page_info": {
         *         "has_more": false
         *       }
         *     }
         * @example {
         *       "items": [
         *         "<one element>"
         *       ],
         *       "page_info": {
         *         "has_more": true,
         *         "next_cursor": "eyJwYWdlIjoxfQ=="
         *       }
         *     }
         */
        CollectionListResponse: {
            /**
             * Items
             * @description Page elements.
             */
            items: components["schemas"]["CollectionSummary"][];
            /** @description Pagination cursor info. */
            page_info: components["schemas"]["PageInfo"];
        };
        /**
         * CollectionSummary
         * @description Lightweight collection row for the list endpoint.
         * @example {
         *       "chunk_count": 1820,
         *       "created_at": "2026-07-15T03:11:08.012Z",
         *       "description": "Internal HR & policies.",
         *       "document_count": 12,
         *       "id": "b2c1f0e8-1234-5678-9abc-def012345678",
         *       "name": "company-handbook",
         *       "updated_at": "2026-07-31T08:25:42.001Z"
         *     }
         */
        CollectionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Name
             * @description Human-readable collection name.
             */
            name: string;
            /**
             * Description
             * @description Optional long-form description.
             */
            description?: string | null;
            /**
             * Document Count
             * @description Number of documents currently indexed.
             * @default 0
             */
            document_count: number;
            /**
             * Chunk Count
             * @description Total chunks indexed across all documents.
             * @default 0
             */
            chunk_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CollectionUpdateRequest
         * @description ``PATCH /collections/{id}`` body.
         */
        CollectionUpdateRequest: {
            /**
             * Description
             * @description Updated description; null clears it.
             */
            description: string | null;
        };
        /**
         * DependencyHealth
         * @description Per-dependency health for ``/system/health``.
         * @example {
         *       "name": "chroma",
         *       "status": "ok"
         *     }
         */
        DependencyHealth: {
            /**
             * Name
             * @description Dependency key (e.g. 'chroma', 'bm25').
             */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "down";
            /**
             * Detail
             * @description Optional short message for the diagnostic page.
             */
            detail?: string | null;
        };
        /**
         * DocumentDetail
         * @description ``GET /documents/{id}`` response — extends summary with ingestion refs.
         *
         *     ``last_task_id`` lets the frontend jump straight to the task detail
         *     page when ``status`` is anything other than ``ready``.
         * @example {
         *       "chunk_count": 142,
         *       "collection_id": "b2c1f0e8-1234-5678-9abc-def012345678",
         *       "created_at": "2026-07-31T08:23:11.234Z",
         *       "file_hash": "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2",
         *       "filename": "employee-handbook.pdf",
         *       "id": "7d4a1c3e-2b0a-4d2c-8e9f-1a2b3c4d5e6f",
         *       "image_count": 7,
         *       "last_query_id": "9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d",
         *       "last_task_id": "1f2e3d4c-5b6a-4c8d-9e0f-1a2b3c4d5e6f",
         *       "size_bytes": 1845632,
         *       "status": "ready",
         *       "updated_at": "2026-07-31T08:25:42.001Z"
         *     }
         */
        DocumentDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Collection Id
             * Format: uuid
             */
            collection_id: string;
            /**
             * Filename
             * @description Original filename.
             */
            filename: string;
            /**
             * Size Bytes
             * @description Raw file size in bytes.
             */
            size_bytes: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "ready" | "failed" | "deleting";
            /**
             * Chunk Count
             * @description Number of chunks written to the vector store.
             * @default 0
             */
            chunk_count: number;
            /**
             * Image Count
             * @description Number of images extracted and indexed.
             * @default 0
             */
            image_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * File Hash
             * @description SHA-256 of the raw file. Used to detect duplicate uploads.
             */
            file_hash?: string | null;
            /**
             * Last Task Id
             * @description Most recent ingestion task ID, if any.
             */
            last_task_id?: string | null;
            /**
             * Last Query Id
             * @description Most recent query that cited this document, if any (M3 batch 2). Lets the UI jump from a document back to the query's trace.
             */
            last_query_id?: string | null;
            /** @description Structured error from the last failed task (if any). Same shape as the top-level HTTP error envelope — branch on ``last_error.code``. */
            last_error?: components["schemas"]["TaskError"] | null;
        };
        /**
         * DocumentListResponse
         * @description ``GET /collections/{id}/documents`` response.
         *
         *     Example (empty collection)::
         *
         *         {
         *           "items": [],
         *           "page_info": {"next_cursor": null, "has_more": false}
         *         }
         * @example {
         *       "items": [],
         *       "page_info": {
         *         "has_more": false
         *       }
         *     }
         * @example {
         *       "items": [
         *         "<one element>"
         *       ],
         *       "page_info": {
         *         "has_more": true,
         *         "next_cursor": "eyJwYWdlIjoxfQ=="
         *       }
         *     }
         */
        DocumentListResponse: {
            /**
             * Items
             * @description Page elements.
             */
            items: components["schemas"]["DocumentSummary"][];
            /** @description Pagination cursor info. */
            page_info: components["schemas"]["PageInfo"];
        };
        /**
         * DocumentSummary
         * @description Lightweight row for collection document list.
         * @example {
         *       "chunk_count": 142,
         *       "collection_id": "b2c1f0e8-1234-5678-9abc-def012345678",
         *       "created_at": "2026-07-31T08:23:11.234Z",
         *       "filename": "employee-handbook.pdf",
         *       "id": "7d4a1c3e-2b0a-4d2c-8e9f-1a2b3c4d5e6f",
         *       "image_count": 7,
         *       "size_bytes": 1845632,
         *       "status": "ready",
         *       "updated_at": "2026-07-31T08:25:42.001Z"
         *     }
         */
        DocumentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Collection Id
             * Format: uuid
             */
            collection_id: string;
            /**
             * Filename
             * @description Original filename.
             */
            filename: string;
            /**
             * Size Bytes
             * @description Raw file size in bytes.
             */
            size_bytes: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "ready" | "failed" | "deleting";
            /**
             * Chunk Count
             * @description Number of chunks written to the vector store.
             * @default 0
             */
            chunk_count: number;
            /**
             * Image Count
             * @description Number of images extracted and indexed.
             * @default 0
             */
            image_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DocumentUploadResponse
         * @description ``POST /collections/{id}/documents`` response.
         *
         *     The synchronous-first design returns the created document + the
         *     ingestion task ID immediately. The frontend then polls ``/tasks/{id}``
         *     for status (no SSE in M1 — see TODO M3 #18).
         * @example {
         *       "document": {
         *         "chunk_count": 0,
         *         "collection_id": "b2c1f0e8-1234-5678-9abc-def012345678",
         *         "created_at": "2026-07-31T08:23:11.234Z",
         *         "filename": "q2-roadmap.pdf",
         *         "id": "7d4a1c3e-2b0a-4d2c-8e9f-1a2b3c4d5e6f",
         *         "image_count": 0,
         *         "size_bytes": 524288,
         *         "status": "pending",
         *         "updated_at": "2026-07-31T08:23:11.234Z"
         *       },
         *       "task_id": "1f2e3d4c-5b6a-4c8d-9e0f-1a2b3c4d5e6f"
         *     }
         */
        DocumentUploadResponse: {
            document: components["schemas"]["DocumentDetail"];
            /**
             * Task Id
             * Format: uuid
             * @description Ingestion task ID; poll ``GET /tasks/{id}`` for status.
             */
            task_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KnowledgeBaseHealth */
        KnowledgeBaseHealth: {
            /** Document Count */
            document_count: number;
            /** Chunk Count */
            chunk_count: number;
            /**
             * Index Status
             * @enum {string}
             */
            index_status: "ready" | "indexing" | "attention";
            /** Last Updated At */
            last_updated_at?: string | null;
        };
        /** KnowledgeBaseMetric */
        KnowledgeBaseMetric: {
            /**
             * Collection Id
             * Format: uuid
             */
            collection_id: string;
            /** Name */
            name: string;
            /** Query Count */
            query_count: number;
            /** No Result Rate */
            no_result_rate?: number | null;
            /** P95 Latency Ms */
            p95_latency_ms?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "attention";
        };
        /** MCPKeyCreateRequest */
        MCPKeyCreateRequest: {
            /** Name */
            name: string;
            /** Allowed Collections */
            allowed_collections: string[];
        };
        /** MCPKeyListResponse */
        MCPKeyListResponse: {
            /** Items */
            items: components["schemas"]["MCPKeyMetadata"][];
        };
        /** MCPKeyMetadata */
        MCPKeyMetadata: {
            /** Key Id */
            key_id: string;
            /** Name */
            name: string;
            /** Allowed Collections */
            allowed_collections: string[];
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Revoked At */
            revoked_at: string | null;
            /** Last Used At */
            last_used_at: string | null;
        };
        /** MCPKeyRenameRequest */
        MCPKeyRenameRequest: {
            /** Name */
            name: string;
        };
        /**
         * MCPKeySecretResponse
         * @description Returned only by create/rotate; ``api_key`` is never listable.
         */
        MCPKeySecretResponse: {
            /** Key Id */
            key_id: string;
            /** Name */
            name: string;
            /** Allowed Collections */
            allowed_collections: string[];
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Revoked At */
            revoked_at: string | null;
            /** Last Used At */
            last_used_at: string | null;
            /** Api Key */
            api_key: string;
        };
        /** OverviewAttentionItem */
        OverviewAttentionItem: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "warning" | "critical";
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Href */
            href: string;
        };
        /** OverviewCoreMetrics */
        OverviewCoreMetrics: {
            effective_retrieval_rate: components["schemas"]["OverviewMetric"];
            p95_latency_ms: components["schemas"]["OverviewMetric"];
            no_result_rate: components["schemas"]["OverviewMetric"];
            ingestion_success_rate: components["schemas"]["OverviewMetric"];
        };
        /** OverviewCorpus */
        OverviewCorpus: {
            /** Collection Count */
            collection_count: number;
            /** Document Count */
            document_count: number;
            /** Chunk Count */
            chunk_count: number;
        };
        /**
         * OverviewMetric
         * @description Current and previous-period value for one decision metric.
         */
        OverviewMetric: {
            /** Value */
            value?: number | null;
            /** Previous */
            previous?: number | null;
            /** Target */
            target?: number | null;
        };
        /** OverviewResponse */
        OverviewResponse: {
            /**
             * Range
             * @enum {string}
             */
            range: "24h" | "7d" | "30d";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Ended At
             * Format: date-time
             */
            ended_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "attention" | "critical";
            /** Headline */
            headline: string;
            /** Summary */
            summary: string;
            /** Query Count */
            query_count: number;
            /** Previous Query Count */
            previous_query_count: number;
            /** Degraded Rate */
            degraded_rate?: number | null;
            /** Failed Ingestions */
            failed_ingestions: number;
            corpus: components["schemas"]["OverviewCorpus"];
            traffic: components["schemas"]["TrafficMetrics"];
            retrieval_health: components["schemas"]["RetrievalHealth"];
            knowledge_base_health: components["schemas"]["KnowledgeBaseHealth"];
            metrics: components["schemas"]["OverviewCoreMetrics"];
            /** Trend */
            trend: components["schemas"]["OverviewTrendPoint"][];
            /** Attention */
            attention: components["schemas"]["OverviewAttentionItem"][];
            /** Knowledge Bases */
            knowledge_bases: components["schemas"]["KnowledgeBaseMetric"][];
        };
        /** OverviewTrendPoint */
        OverviewTrendPoint: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Query Count
             * @default 0
             */
            query_count: number;
            /** Effective Retrieval Rate */
            effective_retrieval_rate?: number | null;
            /** P95 Latency Ms */
            p95_latency_ms?: number | null;
        };
        /**
         * PageInfo
         * @description Cursor pagination metadata.
         *
         *     The cursor is opaque to clients; they should pass back whatever
         *     ``next_cursor`` they got in the previous response.
         *
         *     ``next_cursor`` is required + nullable: every response carries the
         *     field, with ``null`` meaning "no more pages". This avoids the
         *     front-end having to distinguish between "field missing" and
         *     "field is null".
         * @example {
         *       "has_more": true,
         *       "next_cursor": "eyJwYWdlIjoyfQ=="
         *     }
         */
        PageInfo: {
            /**
             * Next Cursor
             * @description Opaque cursor for the next page. ``null`` means no more pages.
             */
            next_cursor: string | null;
            /**
             * Has More
             * @description Convenience flag; equivalent to ``next_cursor is not None``.
             */
            has_more: boolean;
        };
        /**
         * ProviderStatus
         * @description Per-Provider presence + readiness.
         *
         *     The ``configured`` and ``ready`` booleans are the only signals the
         *     frontend should depend on. Detailed model names are exposed because
         *     the Web overview page needs them, but secrets are NEVER returned.
         * @example {
         *       "configured": true,
         *       "model": "gpt-4o-mini",
         *       "ready": true
         *     }
         */
        ProviderStatus: {
            /**
             * Configured
             * @description Whether the Provider has the required configuration (without exposing the value).
             */
            configured: boolean;
            /**
             * Ready
             * @description Whether the Provider is currently reachable / usable.
             */
            ready: boolean;
            /**
             * Model
             * @description Configured model name, if any. Omitted if not configured.
             */
            model?: string | null;
        };
        /**
         * QueryDiagnostics
         * @description Per-stage counts, latency, and degradation signals.
         *
         *     Listed in the v0.1 contract — frontend may render these on the
         *     Playground / Trace page. All counts are nullable so the backend
         *     can skip reporting a stage it didn't run (e.g. rerank when
         *     ``enable_rerank=false``).
         * @example {
         *       "degraded": false,
         *       "degraded_reasons": [],
         *       "dense_count": 20,
         *       "duration_ms": 128,
         *       "fused_count": 15,
         *       "reranked_count": 5,
         *       "sparse_count": 20,
         *       "trace_id": "9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d"
         *     }
         */
        QueryDiagnostics: {
            /**
             * Duration Ms
             * @description End-to-end latency in milliseconds.
             */
            duration_ms: number;
            /**
             * Trace Id
             * @description Trace ID for this query; pass to ``GET /queries/{query_id}/trace`` for the full per-stage breakdown.
             */
            trace_id?: string | null;
            /**
             * Dense Count
             * @description Chunks returned by the dense retriever.
             */
            dense_count?: number | null;
            /**
             * Sparse Count
             * @description Chunks returned by the sparse retriever.
             */
            sparse_count?: number | null;
            /**
             * Fused Count
             * @description Chunks after RRF fusion.
             */
            fused_count?: number | null;
            /**
             * Reranked Count
             * @description Chunks after rerank (0 if skipped).
             */
            reranked_count?: number | null;
            /**
             * Degraded
             * @description True if at least one stage fell back due to a failure.
             * @default false
             */
            degraded: boolean;
            /**
             * Degraded Reasons
             * @description Human-readable reasons; frontend should display but never branch business logic on these strings. Use ``degraded`` for the boolean.
             */
            degraded_reasons?: string[];
        };
        /**
         * QueryRequest
         * @description ``POST /collections/{id}/queries`` body.
         * @example {
         *       "enable_rerank": true,
         *       "mode": "hybrid",
         *       "query": "公司年假怎么规定?",
         *       "top_k": 5
         *     }
         */
        QueryRequest: {
            /**
             * Query
             * @description User question / search string.
             */
            query: string;
            /**
             * Top K
             * @description Maximum number of chunks to return. Hard-capped to 50.
             * @default 5
             */
            top_k: number;
            /**
             * Mode
             * @description Retrieval mode: hybrid (default), dense-only, or sparse-only.
             * @default hybrid
             * @enum {string}
             */
            mode: "hybrid" | "dense" | "sparse";
            /**
             * Enable Rerank
             * @description If false, the rerank stage is skipped. Equivalent to disabling the rerank provider in settings but for a single request.
             * @default true
             */
            enable_rerank: boolean;
        };
        /**
         * QueryResponse
         * @description ``POST /collections/{id}/queries`` response.
         *
         *     ``query_id`` is the query record ID; pass it to
         *     ``GET /queries/{id}/trace`` for the full Trace JSON.
         *     ``answer`` is null in v0.1 — final answer generation is out of scope
         *     (see PRODUCTION §10 "final answer generation as optional independent stage").
         * @example {
         *       "citations": [
         *         {
         *           "chunk_id": "d2c3v4b5n6m7",
         *           "document_id": "7d4a1c3e-2b0a-4d2c-8e9f-1a2b3c4d5e6f",
         *           "document_name": "employee-handbook.pdf",
         *           "images": [],
         *           "index": 1,
         *           "page": 12,
         *           "scores": {
         *             "dense": 0.81,
         *             "fusion": 0.031,
         *             "rerank": 0.91,
         *             "sparse": 8.2
         *           },
         *           "text": "员工年假标准：入职满 1 年不满 10 年，每年 5 天；…"
         *         }
         *       ],
         *       "diagnostics": {
         *         "degraded": false,
         *         "degraded_reasons": [],
         *         "dense_count": 20,
         *         "duration_ms": 128,
         *         "fused_count": 15,
         *         "reranked_count": 5,
         *         "sparse_count": 20,
         *         "trace_id": "9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d"
         *       },
         *       "query_id": "9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d"
         *     }
         * @example {
         *       "citations": [],
         *       "diagnostics": {
         *         "degraded": true,
         *         "degraded_reasons": [
         *           "no chunks matched the query"
         *         ],
         *         "dense_count": 0,
         *         "duration_ms": 42,
         *         "fused_count": 0,
         *         "reranked_count": 0,
         *         "sparse_count": 0,
         *         "trace_id": "9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d"
         *       },
         *       "query_id": "9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d"
         *     }
         * @example {
         *       "citations": [
         *         {
         *           "chunk_id": "d2c3v4b5n6m7",
         *           "document_id": "7d4a1c3e-2b0a-4d2c-8e9f-1a2b3c4d5e6f",
         *           "document_name": "employee-handbook.pdf",
         *           "images": [],
         *           "index": 1,
         *           "page": 12,
         *           "scores": {
         *             "dense": 0.81,
         *             "fusion": 0.031
         *           },
         *           "text": "员工年假标准：…"
         *         }
         *       ],
         *       "diagnostics": {
         *         "degraded": true,
         *         "degraded_reasons": [
         *           "sparse backend unavailable; dense-only fallback",
         *           "rerank timeout; using fused ranking"
         *         ],
         *         "dense_count": 20,
         *         "duration_ms": 96,
         *         "fused_count": 15,
         *         "trace_id": "9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d"
         *       },
         *       "query_id": "9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d"
         *     }
         */
        QueryResponse: {
            /**
             * Query Id
             * Format: uuid
             */
            query_id: string;
            /**
             * Answer
             * @description Final answer text. In v0.1 this is ``null`` — we return chunks and citations, not generated answers. See PRODUCTION §10.
             */
            answer?: string | null;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            diagnostics: components["schemas"]["QueryDiagnostics"];
        };
        /** RetrievalHealth */
        RetrievalHealth: {
            /** Success Rate */
            success_rate?: number | null;
            /** Empty Retrieval Rate */
            empty_retrieval_rate?: number | null;
            /** Average Top K */
            average_top_k?: number | null;
            /** Average Latency Ms */
            average_latency_ms?: number | null;
            /**
             * Rerank Success Rate
             * @description Unavailable while reranking is not enabled/instrumented.
             */
            rerank_success_rate?: number | null;
        };
        /**
         * SystemHealth
         * @description ``GET /system/health`` response.
         *
         *     Top-level ``status`` is the worst of any dependency — frontend should
         *     show a banner when this is anything other than ``ok``.
         * @example {
         *       "dependencies": [
         *         {
         *           "name": "chroma",
         *           "status": "ok"
         *         },
         *         {
         *           "name": "bm25",
         *           "status": "ok"
         *         }
         *       ],
         *       "status": "ok"
         *     }
         * @example {
         *       "dependencies": [
         *         {
         *           "name": "chroma",
         *           "status": "ok"
         *         },
         *         {
         *           "detail": "vision provider not configured",
         *           "name": "vision",
         *           "status": "down"
         *         }
         *       ],
         *       "status": "degraded"
         *     }
         */
        SystemHealth: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "down";
            /** Dependencies */
            dependencies?: components["schemas"]["DependencyHealth"][];
        };
        /**
         * SystemInfo
         * @description ``GET /system/info`` response.
         *
         *     Exposes the pluggable component layout + a per-Provider status map.
         * @example {
         *       "app_name": "skdy-rag-server",
         *       "features": {
         *         "image_captioning": false,
         *         "multimodal": false
         *       },
         *       "providers": {
         *         "embedding": {
         *           "configured": true,
         *           "model": "text-embedding-3-small",
         *           "ready": true
         *         },
         *         "llm": {
         *           "configured": true,
         *           "model": "gpt-4o-mini",
         *           "ready": true
         *         },
         *         "vision": {
         *           "configured": false,
         *           "ready": false
         *         }
         *       },
         *       "rerank_backend": "none",
         *       "sparse_backend": "bm25",
         *       "storage_backend": "chroma",
         *       "version": "0.1.0"
         *     }
         */
        SystemInfo: {
            /**
             * App Name
             * @description Service name (skdy-rag-server).
             */
            app_name: string;
            /**
             * Version
             * @description Service version.
             */
            version: string;
            /**
             * Storage Backend
             * @description Vector store backend identifier (e.g. 'chroma').
             */
            storage_backend: string;
            /**
             * Sparse Backend
             * @description Sparse retrieval backend (e.g. 'bm25').
             */
            sparse_backend: string;
            /**
             * Rerank Backend
             * @description Active rerank backend.
             * @enum {string}
             */
            rerank_backend: "none" | "cross_encoder" | "llm";
            /**
             * Providers
             * @description Map of component name (llm / embedding / vision) to its status. NEVER contains credentials.
             */
            providers: {
                [key: string]: components["schemas"]["ProviderStatus"];
            };
            /**
             * Features
             * @description Optional capability flags (e.g. multimodal, image_captioning). Web UI may use these to hide unsupported actions.
             */
            features?: {
                [key: string]: boolean;
            };
        };
        /**
         * TaskError
         * @description Structured error for async business operations.
         *
         *     Lives inside :class:`TaskStatusResponse` and
         *     :class:`DocumentDetail` (as ``last_error``). Same shape and
         *     branching rules as the top-level HTTP :class:`ErrorDetail`, but
         *     scoped to "this thing I asked you to do, eventually failed" rather
         *     than "this request couldn't even be processed".
         * @example {
         *       "code": "UPSTREAM_ERROR",
         *       "details": {
         *         "provider": "openai",
         *         "status_code": 502
         *       },
         *       "message": "Embedding provider failed"
         *     }
         * @example {
         *       "code": "UNSUPPORTED_FILE_TYPE",
         *       "details": {
         *         "received_content_type": "text/plain"
         *       },
         *       "message": "File content-type 'text/plain' is not allowed"
         *     }
         */
        TaskError: {
            /**
             * Code
             * @description Stable machine-readable code. Frontend branches on this, NEVER on ``message``. Same vocabulary as the top-level HTTP error envelope (``ErrorDetail.code``).
             * @example UPSTREAM_ERROR
             */
            code: string;
            /**
             * Message
             * @description Human-readable error description.
             */
            message: string;
            /**
             * Details
             * @description Optional structured context (e.g. provider name, status code).
             */
            details?: {
                [key: string]: unknown;
            };
        };
        /**
         * TaskProgress
         * @description Structured progress for the current pipeline stage.
         *
         *     ``percent`` is the canonical value the frontend should display
         *     (0–100). ``current``/``total`` stay for diagnostic views and are
         *     nullable when the backend can't predict totals (e.g. some LLM
         *     transforms).
         * @example {
         *       "current": 32,
         *       "message": "Embedding chunks",
         *       "percent": 32,
         *       "stage": "embed",
         *       "total": 100
         *     }
         */
        TaskProgress: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "load" | "split" | "transform" | "embed" | "upsert";
            /**
             * Current
             * @description Items processed in this stage; ``null`` when unknown.
             */
            current?: number | null;
            /**
             * Total
             * @description Items expected in this stage; ``null`` when unknown.
             */
            total?: number | null;
            /**
             * Percent
             * @description Computed by the backend (0–100). Frontend must NOT recompute; different stages use different denominators.
             */
            percent: number;
            /**
             * Message
             * @description Short human-readable hint. Frontend may display but must NOT branch business logic on it.
             */
            message?: string | null;
        };
        /**
         * TaskStatusResponse
         * @description ``GET /tasks/{id}`` response.
         * @example {
         *       "attempt": 0,
         *       "collection_id": "b2c1f0e8-1234-5678-9abc-def012345678",
         *       "created_at": "2026-07-31T08:23:11.234Z",
         *       "document_id": "7d4a1c3e-2b0a-4d2c-8e9f-1a2b3c4d5e6f",
         *       "id": "1f2e3d4c-5b6a-4c8d-9e0f-1a2b3c4d5e6f",
         *       "progress": {
         *         "current": 32,
         *         "message": "Embedding chunks",
         *         "percent": 32,
         *         "stage": "embed",
         *         "total": 100
         *       },
         *       "status": "running",
         *       "updated_at": "2026-07-31T08:23:42.100Z"
         *     }
         * @example {
         *       "attempt": 0,
         *       "collection_id": "b2c1f0e8-1234-5678-9abc-def012345678",
         *       "created_at": "2026-07-31T08:23:11.234Z",
         *       "document_id": "7d4a1c3e-2b0a-4d2c-8e9f-1a2b3c4d5e6f",
         *       "finished_at": "2026-07-31T08:25:42.001Z",
         *       "id": "1f2e3d4c-5b6a-4c8d-9e0f-1a2b3c4d5e6f",
         *       "progress": {
         *         "current": 142,
         *         "percent": 100,
         *         "stage": "upsert",
         *         "total": 142
         *       },
         *       "status": "succeeded",
         *       "updated_at": "2026-07-31T08:25:42.001Z"
         *     }
         * @example {
         *       "attempt": 0,
         *       "collection_id": "b2c1f0e8-1234-5678-9abc-def012345678",
         *       "created_at": "2026-07-31T08:23:11.234Z",
         *       "document_id": "7d4a1c3e-2b0a-4d2c-8e9f-1a2b3c4d5e6f",
         *       "error": {
         *         "code": "UPSTREAM_ERROR",
         *         "details": {
         *           "provider": "openai",
         *           "status_code": 502
         *         },
         *         "message": "Embedding provider failed"
         *       },
         *       "finished_at": "2026-07-31T08:24:01.500Z",
         *       "id": "1f2e3d4c-5b6a-4c8d-9e0f-1a2b3c4d5e6f",
         *       "progress": {
         *         "current": 32,
         *         "message": "Embedding chunks",
         *         "percent": 32,
         *         "stage": "embed",
         *         "total": 100
         *       },
         *       "status": "failed",
         *       "updated_at": "2026-07-31T08:24:01.500Z"
         *     }
         */
        TaskStatusResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Collection Id
             * Format: uuid
             */
            collection_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "succeeded" | "failed" | "cancelled" | "skipped";
            /** @description Current stage + progress. ``None`` when status is ``pending`` or any terminal state. */
            progress?: components["schemas"]["TaskProgress"] | null;
            /**
             * Attempt
             * @description Retry attempt count (0 for first try).
             * @default 0
             */
            attempt: number;
            /** @description Structured error when the task finished in a failed state. Same shape as the top-level HTTP error envelope — frontend branches on ``error.code``, never on ``error.message``. ``None`` for any non-failed status. */
            error?: components["schemas"]["TaskError"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * TraceResponse
         * @description ``GET /queries/{id}/trace`` and ``GET /ingestions/{id}/trace`` response.
         * @example {
         *       "finished_at": "2026-07-31T08:23:11.362Z",
         *       "id": "9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d",
         *       "stages": [
         *         {
         *           "details": {
         *             "top_k": 20
         *           },
         *           "duration_ms": 60,
         *           "method": "cosine",
         *           "name": "dense",
         *           "provider": "openai",
         *           "started_at": "2026-07-31T08:23:11.250Z"
         *         },
         *         {
         *           "details": {
         *             "top_k": 20
         *           },
         *           "duration_ms": 12,
         *           "method": "bm25",
         *           "name": "sparse",
         *           "provider": "bm25",
         *           "started_at": "2026-07-31T08:23:11.250Z"
         *         },
         *         {
         *           "details": {
         *             "k": 60
         *           },
         *           "duration_ms": 2,
         *           "method": "rrf",
         *           "name": "fusion",
         *           "provider": "rrf",
         *           "started_at": "2026-07-31T08:23:11.315Z"
         *         },
         *         {
         *           "details": {
         *             "input_count": 15,
         *             "output_count": 5
         *           },
         *           "duration_ms": 23.4,
         *           "method": "cross_encoder",
         *           "name": "rerank",
         *           "provider": "cross-encoder/ms-marco-MiniLM-L-6-v2",
         *           "started_at": "2026-07-31T08:23:11.350Z"
         *         }
         *       ],
         *       "started_at": "2026-07-31T08:23:11.234Z",
         *       "total_latency_ms": 128,
         *       "trace_type": "query"
         *     }
         */
        TraceResponse: {
            /**
             * Id
             * Format: uuid
             * @description Trace ID (== query or ingestion ID).
             */
            id: string;
            /**
             * Trace Type
             * @description Trace discriminator; one of ``query``, ``ingestion``.
             * @enum {string}
             */
            trace_type: "query" | "ingestion";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /** Total Latency Ms */
            total_latency_ms: number;
            /** Stages */
            stages?: components["schemas"]["TraceStage"][];
            /**
             * Error
             * @description Top-level error message if any.
             */
            error?: string | null;
        };
        /**
         * TraceStage
         * @description One stage inside a trace.
         *
         *     ``method`` / ``provider`` are the dynamic-component hints the
         *     Dashboard already uses to render provider-specific detail
         *     (see DEV_SPEC §3.4.4 / §3.4.5).
         * @example {
         *       "details": {
         *         "input_count": 15,
         *         "output_count": 5
         *       },
         *       "duration_ms": 23.4,
         *       "method": "cross_encoder",
         *       "name": "rerank",
         *       "provider": "cross-encoder/ms-marco-MiniLM-L-6-v2",
         *       "started_at": "2026-07-31T08:23:11.350Z"
         *     }
         */
        TraceStage: {
            /**
             * Name
             * @description Stage name, e.g. 'dense', 'sparse', 'rerank'.
             */
            name: string;
            /**
             * Method
             * @description Implementation method, e.g. 'bm25', 'rrf'.
             */
            method?: string | null;
            /**
             * Provider
             * @description Provider name, e.g. 'openai', 'cross_encoder'.
             */
            provider?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Duration Ms
             * @description Stage duration in milliseconds.
             */
            duration_ms: number;
            /**
             * Details
             * @description Provider-specific or method-specific extra fields.
             */
            details?: {
                [key: string]: unknown;
            };
        };
        /**
         * TrafficMetrics
         * @description Traffic + embedding token accounting (PRD docs/prd-embedding-token-metrics.md).
         *
         *     The three token fields are a unit: either all are numbers (accounting
         *     is live for the window) or all are ``null`` (provider can't report
         *     usage, or stats not wired). ``0`` is an honest "measured, nothing
         *     consumed" answer — never converted to ``null``.
         */
        TrafficMetrics: {
            /** Request Count */
            request_count: number;
            /** Previous Request Count */
            previous_request_count: number;
            /** Success Rate */
            success_rate?: number | null;
            /** Average Latency Ms */
            average_latency_ms?: number | null;
            /**
             * Embedding Token Usage
             * @description Embedding input tokens consumed by query and document indexing operations.
             */
            embedding_token_usage?: number | null;
            /**
             * Query Embedding Tokens
             * @description Embedding input tokens consumed by query-text vectorization.
             */
            query_embedding_tokens?: number | null;
            /**
             * Ingestion Embedding Tokens
             * @description Embedding input tokens consumed by document chunk vectorization.
             */
            ingestion_embedding_tokens?: number | null;
            /**
             * Embedding Token Usage Since
             * @description UTC start of the earliest recorded usage event — lets the UI flag partial-period data.
             */
            embedding_token_usage_since?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_system_info_api_v1_system_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
    get_system_health_api_v1_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemHealth"];
                };
            };
        };
    };
    list_collections_api_v1_collections_get: {
        parameters: {
            query?: {
                /** @description Opaque cursor from the previous page's ``next_cursor``. */
                cursor?: string | null;
                /** @description Page size, 1-100. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_collection_api_v1_collections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_api_v1_collections__collection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection ID (UUID). */
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_collection_api_v1_collections__collection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection ID (UUID). */
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_collection_api_v1_collections__collection_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection ID (UUID). */
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_collection_documents_api_v1_collections__collection_id__documents_get: {
        parameters: {
            query?: {
                /** @description Opaque cursor from the previous page's ``next_cursor``. */
                cursor?: string | null;
                /** @description Page size, 1-100. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Collection ID (UUID). */
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_collection_document_api_v1_collections__collection_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection ID (UUID). */
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_collection_document_api_v1_collections__collection_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"] | components["schemas"]["BatchUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Document ID (UUID). */
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Document ID (UUID). */
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ingestion task ID (UUID). */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_metrics_api_v1_metrics_overview_get: {
        parameters: {
            query?: {
                range?: "24h" | "7d" | "30d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_query_api_v1_collections__collection_id__queries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection ID (UUID). */
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Collection not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Embedding provider failed. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_async_query_api_v1_collections__collection_id__queries_async_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection ID (UUID). */
                collection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncQueryAccepted"];
                };
            };
            /** @description Collection not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_async_query_result_api_v1_queries__query_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Query ID (== task id). */
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncQueryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_query_trace_api_v1_queries__query_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Query ID (== trace id). */
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingestion_trace_api_v1_ingestions__ingestion_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ingestion ID (== task id). */
                ingestion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_api_v1_images__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Image ID. */
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/*": unknown;
                };
            };
            /** @description Image not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mcp_keys_api_v1_mcp_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPKeyListResponse"];
                };
            };
        };
    };
    create_mcp_key_api_v1_mcp_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MCPKeyCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPKeySecretResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_mcp_key_api_v1_mcp_keys__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_mcp_key_api_v1_mcp_keys__name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MCPKeyRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPKeyMetadata"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_mcp_key_api_v1_mcp_keys__name__rotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPKeySecretResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_mcp_key_api_v1_mcp_keys__name__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MCPKeyMetadata"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
